### ISSUE TITLE
"[error] File name too long" when running sbt to build android-plugin

### ISSUE THREAD

**Issue by schmichael** [jberkel/android-plugin#13]
When I run sbt to build android-plugin, it fails with:

```
schmichael@drventure:~/src/android-plugin$ sbt publish-local
[info] 
[info] Updating plugins...
[info] :: retrieving :: plugin-definition#plugin-definition_2.7.7 [sync]
[info]  confs: [compile, runtime, test, provided, system, optional, sources, javadoc]
[info]  0 artifacts copied, 10 already retrieved (0kB/36ms)
[success] Plugins updated successfully.
[info] 
[info]  Extracted source plugin ./lib_managed/scala_2.7.7/sxr-publish-0.1.6.jar ...
[info]  Extracted source plugin ./lib_managed/scala_2.7.7/posterous-sbt-0.1.4.jar ...
[info] Recompiling plugin...
[info]    Source analysis: 2 new/modified, 0 indirectly invalidated, 0 removed.
[error] File name too long
[error] one error found
Compilation failed

Hit enter to retry or 'exit' to quit: 
```

The root path of my android-plugin clone:

```
/home/schmichael/src/android-plugin
```

Using:
- Ubuntu 10.04 Lucid
- Sun Java 6.20
- sbt 0.7.4
- scala 2.7.7

**Comment by n8han** [comment]
I've tested with an almost identical configuration, not seeing a problem. Are you sure you're using the 0.7.4 sbt launcher jar?

**Comment by jberkel** [comment]
same here, can't reproduce it. i'm on osx and not linux, but that shouldn't make a difference.

**Comment by liff** [comment]
I got hit by the same bug. In my case it's because of ecryptfs. Its maximum filename length is 143 bytes. Some of the class file names exceed that limit.

For example: `Publish$$anonfun$checkPosterousAction$1$$anonfun$apply$6$$anonfun$apply$7$$anonfun$apply$8$$anonfun$apply$10$$anonfun$apply$11$$anonfun$apply$12$$anonfun$apply$13.class`
is 168 bytes.

See: https://bugs.launchpad.net/ecryptfs/+bug/344878

Building outside the encrypted home directory is a good workaround.
