### ISSUE TITLE
make plugin work with windows

### ISSUE THREAD

**Issue by jberkel** [jberkel/android-plugin#2]
http://github.com/timgilbert/android-plugin/

**Comment by miaubiz** [comment]
the dx command is dx.bat and cannot be executed without the extension.  the other fiels are either .exe or .bat

[error] Error running dx: java.io.IOException: Cannot run program "c:\android-sd
k-windows\platforms\android-2.0\tools\dx": CreateProcess error=2, The system can
not find the file specified

with http://github.com/timgilbert/android-plugin the batch files work ok but the exes still fail for me.

[error] Error running package-debug: java.io.IOException: Cannot run program "c:
\android-sdk-windows\tools\apkbuilder": CreateProcess error=2, The system cannot
 find the file specified

hardcoding the extensions, .bat or .exe to defaultDxName etc. makes it work.

(windows xp sp3, java 1.6.0_17, scala 2.7.7, sbt 0.5.6)

**Comment by timgilbert** [comment]
I'm actually still seeing an error with my forked copy, running versus SDK 4, android version 1.5.  dx runs OK, but it quits with an error (possibly the command-line switches have changed between android versions)?

The command it's running is:

```
C:\dev\android\android-sdk-windows\platforms\android-1.5\tools\dx.bat -JXmx512M --dex --output=C:\Projects\etc\axr\target\classes.dex C:\Projects\etc\axr\target\classes.min.jar
```

...which gives me the error "error: no command specified" and a usage statement.

```
usage:
  dx --dex [--debug] [--verbose] [--positions=<style>] [--no-locals]
  [--no-optimize] [--statistics] [--[no-]optimize-list=<file>] [--no-strict]
  [--keep-classes] [--output=<file>] [--dump-to=<file>] [--dump-width=<n>]
  [--dump-method=<name>[*]] [--verbose-dump] [--no-files] [--core-library]
  [<file>.class | <file>.{zip,jar,apk} | <directory>] ...
```

The command-line seems to be correct, I'm not certain why it's complaining.

**EDIT:** aha.  The problem seems to be that the flag <tt>-JXmx512M</tt> is coming before the <tt>--dex</tt> command.  If I take that away the command-line runs OK.  I'll experiment with this a bit on my fork.

**Comment by timgilbert** [comment]
After some poking around, I've got this working on Win32.  I can't do a push from this network but will do one later this evening.  All the commands seem to be being run correctly, but I'm getting an error "device not found" on the call to adb -e install at the end.  I'm assuming that's my local setup, however.

**Comment by timgilbert** [comment]
Ok, things are working for me in Windows again.  Sending a pull request.

**Comment by jberkel** [comment]
hi tim, the Xmx512M is really needed, otherwise dx will run out of memory (at least when trying building bigger projects). this was definitely the case with sdk 1.5, not sure about 1.6. can you see if you can put it back in again?

**Comment by timgilbert** [comment]
Hi Jan...  Sure, I'll mess with it some locally and get back to you.  I'm guessing there's just something about the order of arguments on Windows that's more fragile than on unix-based OSes.

[Sorry if you get this twice, Chrome doesn't seem to always like github.]

**Comment by timgilbert** [comment]
Unfortunately it doesn't look like there is a current fix for this - it's actually logged already as [android issue 4217](http://code.google.com/p/android/issues/detail?id=4217).  

The good news is that somebody at Google stated it was fixed in an upcoming version (and indeed the .bat file attached to that ticket is better in this regard), so maybe in Android 2.1 or something this will be fixed.

The bad news is that it won't currently work.  I can just mess with the plugin on my fork so that it only omits the flag on Windows for now.  So far I seem to be the only person masochistic enough to develop with these tools on Windows anyways, and my own projects aren't large yet.  ;)

**Comment by timgilbert** [comment]
Ok, I've verified that my latest commit - 61ff866f0cd64f3d00d58bac1822aef95de2c4cd - works on Windows and should preserve the -JXmx values for non-windows platforms (I also made the exact parameter overrideable).  Can you check it out on a non-windows OS when you get a chance?

**Comment by jberkel** [comment]
still works on my box, merged your changes.

**Comment by miaubiz** [comment]
sweet works for me. thanks guys
