### ISSUE TITLE
API Level 10 support

### ISSUE THREAD

**Issue by jonasb** [jberkel/android-plugin#29]
I've set this in my `project/build/MyProject.scala`:
    trait Defaults {
      def androidPlatformName = "android-10"
    }

Which seems to work fine. However, I had a look at the source of `android-plugin` and found that it doesn't support API level 10 in `AndroidProject.platformName2ApiLevel`. It also seems that `platformName2ApiLevel` expects another format, e.g. `android-2.2` instead of `android-8`. Perhaps it would make sense to use one format throughout?

**Comment by n8han** [comment]
I appears that some changes made to support the newer sdks have made it so that that map can not work, so minSdkVersion is used as a fallback. The only place that apiLevel is used is for the google add-ons. If those are broken in some way we can open a new bug. I'm closing this one as I can see no problem specific to API level 10, which I've also tested.
