### ISSUE TITLE
sbt "actions" command does not list android-plugin's actions

### ISSUE THREAD

**Issue by TJC** [jberkel/android-plugin#31]
To reproduce:
1) Create new project with android-plugin
2) cd newproject
3) sbt actions

Observe that only the default sbt actions get listed.

**Comment by n8han** [comment]
This is because the script creates one project with submodules. If you go into sbt's interactive mode, then enter the subproject, e.g.

> project My Android Project

Then you can print the full list of actions.

I'm not sure why the create script uses subprojects instead of just one project, but I assume it was necessary to get the tests to work. If anyone can come up with a working configuration for tests that does not require subprojects, I'll be happy to update the giter8 template I'm working on.

For now I'm going to leave it as it is and close this issue. This is more a quirk of the current version of sbt.

**Comment by TJC** [comment]
May I suggest that, in the absence of a working-as-normal actions command, some kind of documentation is given to explain how to get it to work? I'm sure I'm not the only person confused by this.
